apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: componenta-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
        - path: /a
          pathType: Exact
          backend:
            service:
              name: componenta
              port:
                number: 8081