apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: componentb-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
        - path: /b
          pathType: Exact
          backend:
            service:
              name: componentb
              port: 
                number: 80